import json
import os
import sys

HEADER = [
    "# Generated by source/meta/gen_setting_types.py from resources/app/cli/args.json. Do not edit by hand.",
    "",
    "from typing import Literal",
    "",
]

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ARGS_PATH = os.path.join(ROOT, "resources", "app", "cli", "args.json")
OUT_PATH = os.path.join(ROOT, "source", "classes", "SettingTypes.py")


def alias_name(key):
    return "".join(part.capitalize() for part in key.split("_")) + "Option"


def generate():
    with open(ARGS_PATH, encoding="utf-8") as f:
        args = json.load(f)
    choice_settings = [(k, v["choices"]) for k, v in args.items()
                       if isinstance(v, dict) and "choices" in v]

    lines = list(HEADER)
    for key, choices in choice_settings:
        literal = ", ".join(repr(c) for c in choices)
        lines.append(f"{alias_name(key)} = Literal[{literal}]")
    lines.append("")
    lines.append("SETTING_CHOICES: dict[str, tuple[str, ...]] = {")
    for key, choices in choice_settings:
        items = ", ".join(repr(c) for c in choices)
        comma = "," if len(choices) == 1 else ""
        lines.append(f"    {key!r}: ({items}{comma}),")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv):
    text = generate()
    if "--check" in argv:
        try:
            with open(OUT_PATH, encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = None
        if current != text:
            print("SettingTypes.py is out of date; run source/meta/gen_setting_types.py")
            return 1
        return 0
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
