# Generated by source/meta/gen_setting_types.py from resources/app/cli/args.json. Do not edit by hand.

from typing import Literal

SpoilerOption = Literal['none', 'settings', 'semi', 'full', 'debug']
LogicOption = Literal['noglitches', 'minorglitches', 'owglitches', 'hybridglitches', 'nologic']
ModeOption = Literal['open', 'standard', 'inverted', 'retro']
SwordsOption = Literal['random', 'assured', 'swordless', 'vanilla']
FluteModeOption = Literal['normal', 'active']
BowModeOption = Literal['progressive', 'silvers', 'retro', 'retro_silvers']
GoalOption = Literal['ganon', 'pedestal', 'dungeons', 'triforcehunt', 'trinity', 'crystals', 'ganonhunt', 'completionist']
DifficultyOption = Literal['normal', 'hard', 'expert']
ItemFunctionalityOption = Literal['normal', 'hard', 'expert']
DropshuffleOption = Literal['none', 'keys', 'underworld']
PotteryOption = Literal['none', 'keys', 'dungeon', 'cave', 'cavekeys', 'reduced', 'clustered', 'nonempty', 'lottery']
MixedTravelOption = Literal['prevent', 'allow', 'force']
StandardizePalettesOption = Literal['standardize', 'original']
TimerOption = Literal['none', 'display', 'timed', 'timed-ohko', 'ohko', 'timed-countdown']
ProgressiveOption = Literal['on', 'off', 'random']
AlgorithmOption = Literal['balanced', 'vanilla_fill', 'major_only', 'dungeon_only', 'district']
ShuffleOption = Literal['vanilla', 'simple', 'restricted', 'full', 'swapped', 'crossed', 'insanity', 'dungeonsfull', 'dungeonssimple', 'lite', 'lean']
DoorShuffleOption = Literal['basic', 'partitioned', 'crossed', 'vanilla']
IntensityOption = Literal['3', '2', '1', 'random']
DoorTypeModeOption = Literal['original', 'big', 'all', 'chaos']
TrapDoorModeOption = Literal['vanilla', 'optional', 'boss', 'oneway']
KeyLogicAlgorithmOption = Literal['dangerous', 'partial', 'strict', 'static']
DungeonCountersOption = Literal['default', 'off', 'on', 'pickup']
CrystalsGanonOption = Literal['7', '6', '5', '4', '3', '2', '1', '0', 'random']
CrystalsGtOption = Literal['7', '6', '5', '4', '3', '2', '1', '0', 'random']
BeemizerOption = Literal['4', '3', '2', '1', '0']
OpenpyramidOption = Literal['auto', 'yes', 'no']
LoglevelOption = Literal['info', 'error', 'warning', 'debug']
FastmenuOption = Literal['normal', 'instant', 'double', 'triple', 'quadruple', 'half']
KeyshuffleOption = Literal['none', 'wild', 'universal']
TakeAnyOption = Literal['none', 'random', 'fixed']
AccessibilityOption = Literal['items', 'locations', 'none']
RestrictBossItemsOption = Literal['none', 'mapcompass', 'dungeon']
HeartbeepOption = Literal['normal', 'double', 'half', 'quarter', 'off']
HeartcolorOption = Literal['red', 'blue', 'green', 'yellow', 'random']
OwPalettesOption = Literal['default', 'random', 'blackout']
UwPalettesOption = Literal['default', 'random', 'blackout']
SkullwoodsOption = Literal['original', 'restricted', 'loose', 'followlinked']
LinkedDropsOption = Literal['unset', 'linked', 'independent']
OverworldMapOption = Literal['default', 'compass', 'map']
ShufflebossesOption = Literal['none', 'simple', 'unique', 'full', 'random']
ShuffleenemiesOption = Literal['none', 'shuffled']
EnemyHealthOption = Literal['default', 'easy', 'normal', 'hard', 'expert']
EnemyDamageOption = Literal['default', 'shuffled', 'random']
AnyEnemyLogicOption = Literal['none', 'allow_drops', 'allow_all']
SaveonexitOption = Literal['ask', 'always', 'never']

SETTING_CHOICES: dict[str, tuple[str, ...]] = {
    'spoiler': ('none', 'settings', 'semi', 'full', 'debug'),
    'logic': ('noglitches', 'minorglitches', 'owglitches', 'hybridglitches', 'nologic'),
    'mode': ('open', 'standard', 'inverted', 'retro'),
    'swords': ('random', 'assured', 'swordless', 'vanilla'),
    'flute_mode': ('normal', 'active'),
    'bow_mode': ('progressive', 'silvers', 'retro', 'retro_silvers'),
    'goal': ('ganon', 'pedestal', 'dungeons', 'triforcehunt', 'trinity', 'crystals', 'ganonhunt', 'completionist'),
    'difficulty': ('normal', 'hard', 'expert'),
    'item_functionality': ('normal', 'hard', 'expert'),
    'dropshuffle': ('none', 'keys', 'underworld'),
    'pottery': ('none', 'keys', 'dungeon', 'cave', 'cavekeys', 'reduced', 'clustered', 'nonempty', 'lottery'),
    'mixed_travel': ('prevent', 'allow', 'force'),
    'standardize_palettes': ('standardize', 'original'),
    'timer': ('none', 'display', 'timed', 'timed-ohko', 'ohko', 'timed-countdown'),
    'progressive': ('on', 'off', 'random'),
    'algorithm': ('balanced', 'vanilla_fill', 'major_only', 'dungeon_only', 'district'),
    'shuffle': ('vanilla', 'simple', 'restricted', 'full', 'swapped', 'crossed', 'insanity', 'dungeonsfull', 'dungeonssimple', 'lite', 'lean'),
    'door_shuffle': ('basic', 'partitioned', 'crossed', 'vanilla'),
    'intensity': ('3', '2', '1', 'random'),
    'door_type_mode': ('original', 'big', 'all', 'chaos'),
    'trap_door_mode': ('vanilla', 'optional', 'boss', 'oneway'),
    'key_logic_algorithm': ('dangerous', 'partial', 'strict', 'static'),
    'dungeon_counters': ('default', 'off', 'on', 'pickup'),
    'crystals_ganon': ('7', '6', '5', '4', '3', '2', '1', '0', 'random'),
    'crystals_gt': ('7', '6', '5', '4', '3', '2', '1', '0', 'random'),
    'beemizer': ('4', '3', '2', '1', '0'),
    'openpyramid': ('auto', 'yes', 'no'),
    'loglevel': ('info', 'error', 'warning', 'debug'),
    'fastmenu': ('normal', 'instant', 'double', 'triple', 'quadruple', 'half'),
    'keyshuffle': ('none', 'wild', 'universal'),
    'take_any': ('none', 'random', 'fixed'),
    'accessibility': ('items', 'locations', 'none'),
    'restrict_boss_items': ('none', 'mapcompass', 'dungeon'),
    'heartbeep': ('normal', 'double', 'half', 'quarter', 'off'),
    'heartcolor': ('red', 'blue', 'green', 'yellow', 'random'),
    'ow_palettes': ('default', 'random', 'blackout'),
    'uw_palettes': ('default', 'random', 'blackout'),
    'skullwoods': ('original', 'restricted', 'loose', 'followlinked'),
    'linked_drops': ('unset', 'linked', 'independent'),
    'overworld_map': ('default', 'compass', 'map'),
    'shufflebosses': ('none', 'simple', 'unique', 'full', 'random'),
    'shuffleenemies': ('none', 'shuffled'),
    'enemy_health': ('default', 'easy', 'normal', 'hard', 'expert'),
    'enemy_damage': ('default', 'shuffled', 'random'),
    'any_enemy_logic': ('none', 'allow_drops', 'allow_all'),
    'saveonexit': ('ask', 'always', 'never'),
}
