# workflow name
name: 🔍 Type Check

# fire on
on: [
  push,
  pull_request
]

# stuff to do
jobs:
  pyright:
    name: 🔍 pyright
    runs-on: ubuntu-latest

    steps:
      # call checkout
      - name: ✔️Checkout commit
        uses: actions/checkout@v4.1.4
      # call install python
      - name: 💿Install Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.12"
      # install pyright and requirements
      - name: 💿Install Dependencies
        shell: bash
        run: |
          python -m pip install pyright==1.1.414 -r resources/app/meta/manifests/pip_requirements.txt
      # run pyright baseline gate
      - name: 🔍Run Pyright Baseline Gate
        shell: bash
        run: |
          python resources/ci/typecheck.py
